language: node_js

node_js:
  - 14

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache

stages:
  - check
  # - test
  #   if: env(DIRTY_JOB) = NOTHING

jobs:
  include:
    - stage: check
      script:
        - export DIRTY_JOB=$(source projects_with_changes.sh $TRAVIS_PULL_REQUEST_BRANCH)
        - echo DIRTY_JOB $DIRTY_JOB
    # - stage: test
    #   script:
    #     - echo In Testing...
