language: node_js

node_js:
  - 14

_shared_job: &shared_job
  - echo $NEXT_PATH
  - echo $TRAVIS_BRANCH
  - export DIRTY_JOB=$(source projects-with-changes.sh $TRAVIS_BRANCH)
  - echo DIRTY_JOB $DIRTY_JOB

_next_job: &NEXT_JOB
  - echo "NEXT JOB"

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache

stages:
  - check
  - test

env:
  global:
    - NEXT_PATH=next
    - SKIP=$(source skip.sh)

jobs:
  include:
    # - stage: check
    #   script:
    #     - export DIRTY_JOB=$(source projects-with-changes.sh $TRAVIS_PULL_REQUEST_BRANCH)
    #     - echo DIRTY_JOB -> $DIRTY_JOB
    - stage: test
      if: env(SKIP) = true
      script:
        - ls
        - *shared_job
        - if [[ $DIRTY_JOB != *"test"* ]]; then ${*NEXT_JOB}; fi
        - echo Testing...
      if: env(SKIP) = false
      script:
        - echo skipping...