language: node_js

node_js:
  - 14

_shared_script: &shared_script
  - cd $TRAVIS_BUILD_DIR
  - source travis-scripts/projects-with-changes.sh $TRAVIS_BRANCH

_node_and_next: &NODE_AND_NEXT
  cache:
    directories:
      - $HOME/.cache/yarn
      - node_modules
      - .next/cache

  before_install:
    - cd $TRAVIS_BUILD_DIR
    - source travis-scripts/projects-with-changes.sh $TRAVIS_BRANCH

  install:
    - cd $TRAVIS_BUILD_DIR
    - source travis-scripts/next/install.sh
    - cd $TRAVIS_BUILD_DIR
    - source travis-scripts/node/install.sh

  script:
    - cd $TRAVIS_BUILD_DIR
    - source travis-scripts/next/script.sh
    - cd $TRAVIS_BUILD_DIR
    - source travis-scripts/node/script.sh

env:
  global:
    - NODE_PATH=node
    - NEXT_PATH=next

jobs:
  include:
    - name: Deploy node and next
      <<: *NODE_AND_NEXT
